### ISSUE TITLE
Broken images in bundle

### ISSUE THREAD

**Issue by sebrk** [bitstadium/HockeySDK-Unity-iOS#49] opened 2018-01-29 12:33 UTC
I'm unsure how this is treated as the error seems to have been there for quite some time but there are multiple broken images in the bundle. They are able to render with Windows Explorer but not in Unity3D or Chrome looking directly in the repo online. Probably there are a few meta data bits that are off in the files. Could be more than what is listed below.

Log:

``
[Error] Could not create asset from Assets/Plugins/HockeyAppUnityIOS/HockeySDKResources.bundle/buttonRoundedDelete.png: File could not be read
[Error] Could not create asset from Assets/Plugins/HockeyAppUnityIOS/HockeySDKResources.bundle/bg.png: File could not be read
[Error] Could not create asset from Assets/Plugins/HockeyAppUnityIOS/HockeySDKResources.bundle/Blur@3x.png: File could not be read
[Error] Could not create asset from Assets/Plugins/HockeyAppUnityIOS/HockeySDKResources.bundle/buttonRoundedDelete@2x.png: File could not be read
[Error] Could not create asset from Assets/Plugins/HockeyAppUnityIOS/HockeySDKResources.bundle/FeedbackPlaceholder.png: File could not be read
[Error] Could not create asset from Assets/Plugins/HockeyAppUnityIOS/HockeySDKResources.bundle/buttonRoundedDeleteHighlighted.png: File could not be read
[Error] Could not create asset from Assets/Plugins/HockeyAppUnityIOS/HockeySDKResources.bundle/AppIconPlaceHolder.png: File could not be read
[Error] Could not create asset from Assets/Plugins/HockeyAppUnityIOS/HockeySDKResources.bundle/buttonRoundedRegularHighlighted.png: File could not be read
``
Live example using Chrome: https://github.com/bitstadium/HockeySDK-Unity-iOS/blob/master/Plugins/HockeyAppUnityIOS/HockeySDKResources.bundle/Blur%403x.png

**Comment by MatkovIvan** [comment] 2018-01-29 12:40
Hi,

We already aware of that (duplicate of #48)
This is known [Unity bug](https://issuetracker.unity3d.com/issues/could-not-create-texture-error-is-shown-after-importing-texture). You can safely ignore these warnings for now.

Best,
Ivan

**Comment by sebrk** [comment] 2018-01-29 12:44
I don't think this is a Unity bug per se. The link I provide, directly from this repo has a broken image icon. Photoshop also fails to load the image. Also, I'm running 2017.3 and it is NOT fixed (if this even is a Unity error which I doubt).

**Comment by sebrk** [comment] 2018-01-29 15:03
OK. I can see that the commit updates three images. I however am getting this error on more than three images. Just a notice. I have not checked other commits. Does this get into the Unity bundle soon?

**Comment by bmourat** [comment] 2018-01-29 16:17
actually, i don't know when next unity release will be
@TroubleMakerBen any info on date of next release?

**Comment by TroubleMakerBen** [comment] 2018-01-31 00:13
I cannot confirm a release date for the unity plugin. I'll update this as soon as I have a release date.

**Comment by sebrk** [comment] 2018-01-31 08:23
@TroubleMakerBen ok thanks! I keep this one open as a friendly reminder. Close it when it's updated.

**Comment by TroubleMakerBen** [comment] 2018-01-31 18:40
Of course leave this open. I'd be a horrible person if I'd just close this without a release! =)

Thx for your understanding and for using HockeyApp in the first place!

**Closed** 2020-02-19 14:12 UTC
